spring:
  redis:
    host: 127.0.0.1
    port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 105600541641-kqdm04lknue99qvkm59kih7riuc5ipt3.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile




  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
  data:
    elasticsearch:
      repositories:
        enabled: true
      client:
        reactive:
          endpoints: 127.0.0.1:9200